require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EcomicsController do

  # This should return the minimal set of attributes required to create a valid
  # Ecomic. As you add validations to Ecomic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EcomicsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ecomics as @ecomics" do
      ecomic = Ecomic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ecomics).should eq([ecomic])
    end
  end

  describe "GET show" do
    it "assigns the requested ecomic as @ecomic" do
      ecomic = Ecomic.create! valid_attributes
      get :show, {:id => ecomic.to_param}, valid_session
      assigns(:ecomic).should eq(ecomic)
    end
  end

  describe "GET new" do
    it "assigns a new ecomic as @ecomic" do
      get :new, {}, valid_session
      assigns(:ecomic).should be_a_new(Ecomic)
    end
  end

  describe "GET edit" do
    it "assigns the requested ecomic as @ecomic" do
      ecomic = Ecomic.create! valid_attributes
      get :edit, {:id => ecomic.to_param}, valid_session
      assigns(:ecomic).should eq(ecomic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ecomic" do
        expect {
          post :create, {:ecomic => valid_attributes}, valid_session
        }.to change(Ecomic, :count).by(1)
      end

      it "assigns a newly created ecomic as @ecomic" do
        post :create, {:ecomic => valid_attributes}, valid_session
        assigns(:ecomic).should be_a(Ecomic)
        assigns(:ecomic).should be_persisted
      end

      it "redirects to the created ecomic" do
        post :create, {:ecomic => valid_attributes}, valid_session
        response.should redirect_to(Ecomic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ecomic as @ecomic" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ecomic.any_instance.stub(:save).and_return(false)
        post :create, {:ecomic => { "name" => "invalid value" }}, valid_session
        assigns(:ecomic).should be_a_new(Ecomic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ecomic.any_instance.stub(:save).and_return(false)
        post :create, {:ecomic => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ecomic" do
        ecomic = Ecomic.create! valid_attributes
        # Assuming there are no other ecomics in the database, this
        # specifies that the Ecomic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ecomic.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => ecomic.to_param, :ecomic => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested ecomic as @ecomic" do
        ecomic = Ecomic.create! valid_attributes
        put :update, {:id => ecomic.to_param, :ecomic => valid_attributes}, valid_session
        assigns(:ecomic).should eq(ecomic)
      end

      it "redirects to the ecomic" do
        ecomic = Ecomic.create! valid_attributes
        put :update, {:id => ecomic.to_param, :ecomic => valid_attributes}, valid_session
        response.should redirect_to(ecomic)
      end
    end

    describe "with invalid params" do
      it "assigns the ecomic as @ecomic" do
        ecomic = Ecomic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ecomic.any_instance.stub(:save).and_return(false)
        put :update, {:id => ecomic.to_param, :ecomic => { "name" => "invalid value" }}, valid_session
        assigns(:ecomic).should eq(ecomic)
      end

      it "re-renders the 'edit' template" do
        ecomic = Ecomic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ecomic.any_instance.stub(:save).and_return(false)
        put :update, {:id => ecomic.to_param, :ecomic => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ecomic" do
      ecomic = Ecomic.create! valid_attributes
      expect {
        delete :destroy, {:id => ecomic.to_param}, valid_session
      }.to change(Ecomic, :count).by(-1)
    end

    it "redirects to the ecomics list" do
      ecomic = Ecomic.create! valid_attributes
      delete :destroy, {:id => ecomic.to_param}, valid_session
      response.should redirect_to(ecomics_url)
    end
  end

end
